arb-dir: lib/l10n
template-arb-file: intl_en.arb
synthetic-package: false
nullable-getter: false
untranslated-messages-file: l10n_errors.txt
output-dir: lib/l10n
output-localization-file: app_localizations.dart
